//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CV64_RMG.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_CV64RMG_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDD_INPUT_REMAPPING		104
#define IDD_MEMPAK_EDITOR		105
#define IDD_SAVESTATE_MANAGER	106
#define IDM_ABOUT				107
#define IDM_EXIT				108
#define IDM_SETTINGS			109
#define IDM_INPUT_REMAPPING		110
#define IDM_TOGGLE_FULLSCREEN	111
#define IDM_MEMPAK_EDITOR		112
#define IDM_SAVESTATE_MANAGER	113
#define IDM_MOD_LOADER			114
#define IDM_MODEL_VIEWER		115
#define IDM_GAME_INFO			116
#define IDD_GAME_INFO			117
#define IDI_CV64RMG			110
#define IDI_SMALL				111
#define IDC_CV64RMG			112
#define IDC_ABOUT_LOGO			113
#define IDB_RETRO_LOGO			114
#define IDC_MYICON				2
#define IDC_GAMEINFO_PORTRAIT	3100
#define IDC_GAMEINFO_CHARNAME	3101
#define IDC_GAMEINFO_MAP		3102
#define IDC_GAMEINFO_HP			3103
#define IDC_GAMEINFO_GOLD		3104
#define IDC_GAMEINFO_SUBWEAPON	3105
#define IDC_GAMEINFO_TIME		3106
#define IDC_GAMEINFO_DIFFICULTY	3107
#define IDC_GAMEINFO_STATE		3108
#define IDC_GAMEINFO_POSITION	3109
#define IDC_GAMEINFO_FOG		3110
#define IDC_GAMEINFO_CAMERA		3111
#define IDC_GAMEINFO_BOSS		3112
#define IDC_GAMEINFO_JEWELS		3113
#define IDC_GAMEINFO_SAVEFILE	3114
#define IDC_GAMEINFO_PROCMETER	3115
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32772
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
